### ISSUE TITLE
[Get-PEB] argument transformation on parameter 'Id'

### ISSUE THREAD

**Issue by maximilian578** [mattifestation/PowerShellArsenal#9]
Taken from [.EXAMPLE](https://github.com/mattifestation/PowerShellArsenal/blob/master/WindowsInternals/Get-PEB.ps1#L31)
```
$NotepadPEB = Get-PEB -Id (ps notepad)
Get-PEB : Cannot process argument transformation on parameter 'Id'. Cannot convert the "System.Diagnostics.Process (notepad)" value of type "System.Diagnostics.Process" to type "System.UInt16[]".
At line:1 char:27
+ $NotepadPEB = Get-PEB -Id (ps notepad)
+                           ~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-PEB], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Get-PEB
```
my ps version:

|Major    |Minor    |Build      |Revision |
|---------| ---------| ---------| ---------|
|5           |1            |17763     |316       |

**Comment by jazzdelightsme** [comment]
Looks like the example is just wrong, to me. Should be something like `$NotepadPEB = Get-PEB -Id (ps notepad).Id`.

An possible alternative: `$NotepadPEB = ps notepad | Get-PEB`.

**Comment by maximilian578** [comment]
Got it
